import {
  PerformanceRecommendation,
  PerformanceStats,
  RiskTolerance,
  StockRecommendation,
} from '@market-mind/common';

export const mockPastRecommendations: PerformanceRecommendation[] = [
  {
    id: '1',
    stockSymbol: 'AAPL',
    companyName: 'Apple Inc.',
    status: StockRecommendation.INVEST,
    riskTolerance: RiskTolerance.LOW,
    date: '2024-09-15',
    entryPrice: 165.2,
    currentPrice: 178.52,
    outcome: 'Success',
    returnPct: 8.06,
  },
  {
    id: '2',
    stockSymbol: 'META',
    companyName: 'Meta Platforms',
    status: StockRecommendation.INVEST,
    riskTolerance: RiskTolerance.MEDIUM,
    date: '2024-08-22',
    entryPrice: 485.5,
    currentPrice: 542.8,
    outcome: 'Success',
    returnPct: 11.8,
  },
  {
    id: '3',
    stockSymbol: 'INTC',
    companyName: 'Intel Corporation',
    status: StockRecommendation.EXIT,
    riskTolerance: RiskTolerance.MEDIUM,
    date: '2024-10-01',
    entryPrice: 42.8,
    currentPrice: 31.2,
    outcome: 'Success',
    returnPct: 27.1,
  },
  {
    id: '4',
    stockSymbol: 'DIS',
    companyName: 'Walt Disney',
    status: StockRecommendation.INVEST,
    riskTolerance: RiskTolerance.MEDIUM,
    date: '2024-07-10',
    entryPrice: 98.5,
    currentPrice: 89.3,
    outcome: 'Miss',
    returnPct: -9.34,
  },
  {
    id: '5',
    stockSymbol: 'GOOGL',
    companyName: 'Alphabet Inc.',
    status: StockRecommendation.HOLD,
    riskTolerance: RiskTolerance.LOW,
    date: '2024-09-28',
    entryPrice: 158.2,
    currentPrice: 165.4,
    outcome: 'Success',
    returnPct: 4.55,
  },
  {
    id: '6',
    stockSymbol: 'AMZN',
    companyName: 'Amazon.com',
    status: StockRecommendation.INVEST,
    riskTolerance: RiskTolerance.LOW,
    date: '2024-08-05',
    entryPrice: 168.9,
    currentPrice: 186.5,
    outcome: 'Success',
    returnPct: 10.42,
  },
  {
    id: '7',
    stockSymbol: 'NFLX',
    companyName: 'Netflix Inc.',
    status: StockRecommendation.INVEST,
    riskTolerance: RiskTolerance.HIGH,
    date: '2024-10-12',
    entryPrice: 625.0,
    currentPrice: 712.3,
    outcome: 'Success',
    returnPct: 13.97,
  },
  {
    id: '8',
    stockSymbol: 'BA',
    companyName: 'Boeing Co.',
    status: StockRecommendation.EXIT,
    riskTolerance: RiskTolerance.HIGH,
    date: '2024-09-05',
    entryPrice: 178.4,
    currentPrice: 155.2,
    outcome: 'Success',
    returnPct: 13.0,
  },
];

export const mockPerformanceStats: PerformanceStats = {
  successRate: 88,
  avgReturn: 9.9,
  totalCalls: 8,
  since: 'September 2024',
};
